const USER_STATUS = {
    APPROVED: "APPROVED",
    PENDING: "PENDING",
    REJECTED: "REJECTED"
};

const USER_ROLE = {
    CUSTOMER: "CUSTOMER",
    ADMIN: "ADMIN",
    CLIENT: "CLIENT"
};

const STATUS_CODES = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    TOO_MANY_REQUESTS: 429,
    NOT_IMPLEMENTED: 501,
    GONE: 410
};

const BOOKING_STATUS = {
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    SUCCESSFUL: "SUCCESSFUL",
    CANCELLED: "CANCELLED",
    FAILED: "FAILED",
    ON_HOLD: "ON_HOLD",
    EXPIRED: "EXPIRED",
    RESCHEDULED: "RESCHEDULED",
    PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED",
    AWAITING_REFUND: "AWAITING_REFUND",
    REFUNDED: "REFUNDED"
};

const PAYMENT_STATUS = {
    SUCCESSFUL: "SUCCESSFUL",
    FAILED: "FAILED",
    PENDING: "PENDING",
    REFUNDED: "REFUNDED",
    PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED",
    AWAITING_REFUND: "AWAITING_REFUND",
    CANCELLED: "CANCELLED",
    PROCESSING: "PROCESSING",
    DECLINED: "DECLINED",
    EXPIRED: "EXPIRED"
};

const MONGO_ERRORS = {
    DUPLICATE_KEY: 11000
};

module.exports = {
    USER_ROLE,
    USER_STATUS,
    STATUS: STATUS_CODES,
    BOOKING_STATUS,
    PAYMENT_STATUS,
    MONGO_ERRORS
};
