const USER_STATUS = {
    APPROVED: "APPROVED",
    PENDING: "PENDING",
    REJECTED: "REJECTED"
};

const USER_ROLE = {
    CUSTOMER: "CUSTOMER",
    ADMIN: "ADMIN",
    CLIENT: "CLIENT"
};

const STATUS_CODES = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    INTERNAL_SERVER_ERROR: 500
};

const BOOKING_STATUS = {
    PROCESSING: "PROCESSING",
    SUCCESSFUL: "SUCCESSFUL",
    CANCELLED: "CANCELLED"
};

const PAYMENT_STATUS = {
    SUCCESSFUL: "SUCCESSFUL",
    FAILED: "FAILED",
    PENDING: "PENDING"
};

const MONGO_ERRORS = {
    DUPLICATE_KEY: 11000
};

module.exports = {
    USER_ROLE,
    USER_STATUS,
    STATUS: STATUS_CODES,
    BOOKING_STATUS,
    PAYMENT_STATUS,
    MONGO_ERRORS
};
